config/routes.rb
Rails.application.routes.draw do


  # Main Root
  root 'pages#index', as: 'root'


  # Main Routes
  get 'explore' => 'pages#explore', as: 'explore'
  get 'about' => 'pages#about', as: 'about'


  # SignUp Sources
  get 'signup' => 'registrations#signup', as: 'signup'
  post 'users' => 'registrations#create', as: 'create'


  # Login Sources
  get 'login' => 'sessions#login', as: 'login'
  post 'login' => 'sessions#create', as: 'login-create'
  get 'logout' => 'sessions#destroy', as: 'destroy-login'

  # Admin Sources
  get 'admin' => 'admin#admin', as: 'admin'
  post 'admin' => 'admin#create', as: 'admin_login'
  get 'admin/logout' => 'admin#destroy', as: 'admin_destroy_login'
  get 'admin/dashboard' => 'administration#dashboard', as: 'dashboard'
  get 'admin/dashboard/products' => 'administration#control_products', as: 'control_product'
  get 'admin/dashboard/customers' => 'administration#control_customers', as: 'control_customers'

  # Creation Sources
  post 'admin/dashboard/products' => 'cards#create'
  get 'cards' => 'cards#show'
  get 'cards' => 'cards#edit', as: 'card_edit'
  get 'cards' => 'cards#destroy', as: 'card_delete'
  put 'cards' => 'cards#update', as: 'card_update'
  put "add", to: "cards#library"
  put "remove", to: "cards#library"

  resources :cards do
    resources :comments
  end

  resources :user do
    resources :book
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  has_secure_password
  validates_presence_of :username
  validates_uniqueness_of :username
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user, optional: true
  has_many :books
  has_many :added_cards, through: :books, source: :user
  has_many :comments, dependent: :delete_all
  has_one_attached :cardpic
  has_one_attached :pdffile
  validates :cardname, presence: true, length: { minimum: 2 }
  validates :carddes, presence: true, length: { minimum: 50, maximum: 200 }
  validates :cardprice, presence: true
  validates :cardgen, presence: true
  validates :cardpage, presence: true
  validates :cardyear, presence: true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :card
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :cards, dependent: :destroy
  has_many :books
  has_many :books_additions, through: :books, source: :card
  has_one_attached :avatar
  validates_presence_of :email
  validates_uniqueness_of :email
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  http_basic_authenticate_with name: 'admin', password: 'admin'
  
  # Admin Login
  def admin; end

  # Create Login
  def create
    admin = Admin.find_by(username: params[:username])
    if admin && admin.authenticate(params[:password])
      session[:admin_id] = admin.id
      redirect_to dashboard_path
    else
      render json: {
        session: :dead,
        login: :failed
      }
    end
  end

  # Destroy LogIn
  def destroy
    reset_session
    redirect_to root_path
  end

  # Logged In
  def logged_in
    if @current_admin
      render json: {
        logged_in: true,
        admin: @current_admin
      }

    else
      render json: {
        logged_in: false
      }
    end
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  include CurrentAdminConcern

  # Show Card
  def show
    @card = Card.find(params[:id])
  end

  # New Card
  def new
    @card = Card.new
  end

  # Create Cards
  def create
    @card = Card.new(card_params)

    if @card.save
      redirect_to @card

    else
      render json: {
        status: :dead,
        creation: :denied,
        name: @card.cardname,
        price: @card.cardprice,
        description: @card.carddes,
        genre: @card.cardgen,
        pages: @card.cardpage,
        year: @card.cardyear,
        downloads: @card.carddownload,
        errors: @card.errors.any?,
        info: @card.errors.full_messages.each
      }
    end

  end

  # Edit Cards
  def edit
    if set_current_admin
      @card = Card.find(params[:id])

    else
      render 'pages/404'
    end
  end

  # Update Cards
  def update
    @card = Card.find(params[:id])
    if @card.update(card_params)
      redirect_to @card

    else
      render json: {
          status: :dead,
          creation: :denied,
          name: @card.cardname,
          price: @card.cardprice,
          description: @card.carddes,
          genre: @card.cardgen,
          pages: @card.cardpage,
          year: @card.cardyear,
          downloads: @card.carddownload,
          errors: @card.errors.any?,
          info: @card.errors.full_messages.each
      }
    end
  end

  # Delete Cards
  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to explore_path
  end


  # Card Params
  public def card_params
    params.require(:card).permit(:cardname, :cardprice, :carddes, :cardgen, :cardpage, :cardyear, :carddownload, :cardpremium, :cardpic, :pdffile)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # Main Page
  def index
    @logo = 'BookTalk'
  end

  # Explore Page
  def explore
    @card = Card.all
  end

  # About Page
  def about; end

  # SignUp Page
  def signup; end


  # SignUp Creation
  def create
    user = User.new(
      fname: params[:fname],
      lname: params[:lname],
      email: params[:email],
      password: params[:password]
    )

    if user
      session[:user_id] = user.id
      render json: {
        status: :created,
        user: :user
      }

    else
      render json: { status: 500 }
    end
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  include CurrentUserConcern


  # Profile Page
  def profile
    unless set_current_user
      render 'pages/404'
    end
    @user = User.all
    @user = User.find_by(params[:id])

    @book = Book.all


  end



  # Profile Setting
  def settings
    unless set_current_user
      render 'pages/404'
    end
    @user = User.all
    @user = User.find_by(params[:id])

  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/admin/admin.html.erb
<!DOCTYPE html>
<html>





<!-- Body Contents -->
<body style="background-color: #152734; overflow-x: hidden;">

<!-- Instruct -->
<h1 class="login-instruct text-center">Admin Login</h1>

<!-- Form Control -->
<%= form_tag admin_path, method: :post, :class => 'card login-form' do %>
  <%= image_tag("FormLogo.png", :alt => 'FormImage', :class => 'FormImage') %>

  <!-- Form Contents -->
  <div class="card-body">

    <!-- Email -->
    <%= label_tag :username, 'Username', :class => 'login-email-label' %> <br>
    <%= text_field_tag :username, nil  ,:placeholder => 'Username', :class => 'login-email form-control float-left' %>


    <!-- Password -->
    <%= label_tag :password, 'Password', :class => 'login-password-label' %> <br>
    <%= password_field_tag :password, nil , :placeholder => 'Password', :class => 'login-password form-control float-left' %>

    <br>

    <!-- Finalization -->
    <%= submit_tag "Login", :class => 'signup-button-main btn btn-primary lead' %>

  </div>

<% end %>


<% yield %>
</body>





</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>



    <!-- Meta Tags -->
    <title>BookTalk</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Main Sources -->
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css'%>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js"></script>


    <!-- Font Sources -->
    <link href="https://fonts.googleapis.com/css2?family=Nunito:ital,wght@1,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@1,300&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Balsamiq+Sans:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@700&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Capriola&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet">




  </head>


  <body class="body">
    <%= yield %>
  </body>

</html>

app/views/pages/404.html.erb
<html>

<body style="background-color: #112330;">

  <%= image_tag("404.gif", :alt => '404', :class => 'notfound-style') %>

  <div class="text-center">
    <br> <br> <br>
    <%= link_to "Back To Road", root_path, :class => 'btn btn-primary notfound-button' %>
  </div>

</body>

</html>